[package]
name = "ckb-traits"
version = "0.20.0-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[dependencies]
ckb-types = { path = "../util/types" }
ckb-chain-spec = {path = "../spec"}
ckb-store = { path = "../store" }
ckb-script = { path = "../script" }
ckb-error = { path = "../error" }
