[package]
name = "ckb-tx-pool-executor"
version = "0.20.0-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"

[dependencies]
ckb-shared = { path = ".." }
ckb-types = { path = "../../util/types" }
ckb-store = { path = "../../store" }
ckb-traits = { path = "../../traits" }
ckb-verification = { path = "../../verification" }

numext-fixed-hash = { version = "0.1", features = ["support_rand", "support_heapsize", "support_serde"] }
fnv = "1.0.3"
ckb-error = { path = "../../error" }

[dev-dependencies]
ckb-chain = { path = "../../chain" }
ckb-notify = { path = "../../notify" }
ckb-db = { path = "../../db" }
ckb-chain-spec = { path = "../../spec" }
faketime = "0.2"
ckb-test-chain-utils = { path = "../../util/test-chain-utils" }
